### PR TITLE
Date and UTC feature

### PR DESCRIPTION
**Pull request by bozlo**
Hi,

I added date and utc time out feature.

### CODE REVIEW

**Comment by spessoni** [comment]
Thanks for contributing! Give me a little time and I will see if I can merge this.

**Comment by MrGoogleChat** [comment]
The original script from SPessoni is great.

Your change (adding the date) is a really useful addition.  Will you be able to merge it into the main?

Out of curiosity, will I be able to still use my local time zone offset instead of actual UTC time?

Finally, how can I suppress a leading zero.  For example, I want 4:22 AM, not 04:22 AM.

Once again, thanks to you and SPessoni.

**Comment by MrGoogleChat** [comment]
How can I get a merged version?

**Comment by spessoni** [comment]
My goal is to work on this during the holiday break.

**Comment by MrGoogleChat** [comment]
That would be wonderful.  



I was hoping bozlo would also have some good news regarding the questions I asked him.

 

In any event, Merry Christmas and Happy New Year.

**Comment by MrGoogleChat** [comment]
I should have replied here on the website and not via email.  Sorry for my poor protocol.

**Comment by spessoni** [comment]
I'm going to merge this pull request. I also updated the documentation and fixed a small bug with the 12 hr mode. Thanks for contributing @bozlo.

To answer @MrGoogleChat, by default, it will use you local time offset settings.  If you select the UTC option, it will change to the UTC(GMT) date & time. By design, UTC does not have timezones.  Also, as of yet, there is no way to remove the leading zero.  I think a future version will allow total customization of the display format.

Have a great New Year!

**Comment by MrGoogleChat** [comment]
Scott, I downloaded and installed v1.01.  It works perfectly, as advertised.  

I'm currently using it with UTC/24-hour mode and the leading zero is desirable (for my purpose, it's actually required).  If I were to change to my local PC time with 12-hour AM/PM, the leading zero would not be desirable.

Nevertheless, I'm thrilled with this version and can live with it for quite a while, so no rush from my standpoint to have "total customization" of the display format.

Can't thank you and @bozlo enough.

Stay well, stay safe and Happy New Year!

**Comment by MrGoogleChat** [comment]
Good Morning,

While adding a new video source, I have managed to completely break the Timecode display function.

And I don't remember exactly what I did initially when I first installed/configured the lua a few weeks ago.  

Now there are no choices to select in the "Text Source" dropdown -- it's just blank.

It's probably something simple and I'm just too stupid this morning to figure out the solution.  Can you bail me out?

Thanks.

**Pull request merged**
